services:
  opengravity:
    build: .
    image: opengravity:latest
    container_name: opengravity-bot
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./memory.db:/app/memory.db
      - ./temp_audio:/app/temp_audio
      - ./service-account.json:/app/service-account.json
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
